# Generated by Django 5.1.7 on 2025-04-05 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_cart_created_at_remove_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='house',
        ),
    ]
