# Generated by Django 5.1.7 on 2025-04-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_userprofile_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='house',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
