# Generated by Django 5.1.7 on 2025-04-05 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_userprofile_house'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
