# Generated by Django 5.1.7 on 2025-04-05 19:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=200)),
                ('house', models.CharField(blank=True, max_length=50)),
                ('apartment', models.CharField(blank=True, max_length=50)),
                ('card_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Номер карты должен состоять из 16 цифр.', regex='^\\d{16}$')])),
                ('card_expiry', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message='Срок действия должен быть в формате MM/YY.', regex='^(0[1-9]|1[0-2])/\\d{2}$')])),
                ('card_cvv', models.CharField(blank=True, max_length=3, validators=[django.core.validators.RegexValidator(message='CVV должен состоять из 3 цифр.', regex='^\\d{3}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
