# Generated by Django 5.1.7 on 2025-04-06 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_order_promo_code_remove_userprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
