# Generated by Django 5.1.7 on 2025-04-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(choices=[('MOSCOW', 'Москва'), ('SPB', 'Санкт-Петербург'), ('NOVOSIBIRSK', 'Новосибирск'), ('EKATERINBURG', 'Екатеринбург'), ('KAZAN', 'Казань')], default='MOSCOW', max_length=50),
        ),
    ]
