# Generated by Django 5.1.7 on 2025-04-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_order_address_order_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
    ]
