# Generated by Django 5.1.7 on 2025-04-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_order_user_order_number_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_order_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
