# Generated by Django 5.1.7 on 2025-04-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_order_user_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_order_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
